-- 在庫管理テーブルの作成
CREATE TABLE INVENTORY_CONTROL (
  `INVENTORY_ID` INT NOT NULL COMMENT '在庫ID'
  , `PRODUCT_NAME` VARCHAR(20) COMMENT '商品名'
  , `STOCK` INT COMMENT '在庫数'
  , `PRICE` INT COMMENT '価格'
  , `ORIGIN` VARCHAR(20) COMMENT '産地'
  , `ITEM_TYPE` VARCHAR(20) COMMENT '品目'
  , `CREATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時'
  , `UPDATE_DATE` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時'
  , constraint `PK_INVENTORY_CONTROL` primary key (`INVENTORY_ID`)
)
  COMMENT='在庫管理'
